name: Docker Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag debian-ssh:$(date +%s)
        
      - name: Test build
        run: |
          docker build -t debian-ssh-test .
          container_id=$(docker run -d debian-ssh-test)
          sleep 5
          docker ps | grep debian-ssh-test
          docker logs $container_id
          docker stop $container_id 